# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'SUBSEAGUI.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1308, 1188)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(700, 600))
        font = QFont()
        font.setFamily(u"Arial")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet(u"")
        self.actionNew = QAction(MainWindow)
        self.actionNew.setObjectName(u"actionNew")
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        self.actionCopy = QAction(MainWindow)
        self.actionCopy.setObjectName(u"actionCopy")
        self.actionPaste = QAction(MainWindow)
        self.actionPaste.setObjectName(u"actionPaste")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setMinimumSize(QSize(0, 0))
        self.centralwidget.setStyleSheet(u"QPushButton{ background-color: grey }\n"
"")
        self.gridLayout_7 = QGridLayout(self.centralwidget)
        self.gridLayout_7.setObjectName(u"gridLayout_7")
        self.gridLayout_7.setContentsMargins(10, 10, 10, 10)
        self.drop_shadow_frame = QFrame(self.centralwidget)
        self.drop_shadow_frame.setObjectName(u"drop_shadow_frame")
        self.drop_shadow_frame.setMinimumSize(QSize(0, 0))
        self.drop_shadow_frame.setStyleSheet(u"QFrame#drop_shadow_frame {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(42, 44, 111, 255), stop:0.521368 rgba(28, 29, 73, 255)); border-radius: 10px;\n"
"}")
        self.drop_shadow_frame.setFrameShape(QFrame.NoFrame)
        self.drop_shadow_frame.setFrameShadow(QFrame.Raised)
        self.verticalLayout = QVBoxLayout(self.drop_shadow_frame)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.title_bar = QFrame(self.drop_shadow_frame)
        self.title_bar.setObjectName(u"title_bar")
        self.title_bar.setMinimumSize(QSize(0, 65))
        self.title_bar.setMaximumSize(QSize(16777215, 16777215))
        palette = QPalette()
        brush = QBrush(QColor(33, 33, 75, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush)
        palette.setBrush(QPalette.Active, QPalette.Base, brush)
        palette.setBrush(QPalette.Active, QPalette.Window, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush)
        self.title_bar.setPalette(palette)
        self.title_bar.setLayoutDirection(Qt.LeftToRight)
        self.title_bar.setStyleSheet(u"QFrame#title_bar { border-radius: 10px; \n"
"background-color: rgb(33, 33, 75);}")
        self.title_bar.setFrameShape(QFrame.NoFrame)
        self.title_bar.setFrameShadow(QFrame.Raised)
        self.title_bar.setLineWidth(20)
        self.gridLayout_2 = QGridLayout(self.title_bar)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(12, 0, 12, 0)
        self.buttons_frame = QFrame(self.title_bar)
        self.buttons_frame.setObjectName(u"buttons_frame")
        self.buttons_frame.setFrameShape(QFrame.NoFrame)
        self.buttons_frame.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_5 = QHBoxLayout(self.buttons_frame)
#ifndef Q_OS_MAC
        self.horizontalLayout_5.setSpacing(-1)
#endif
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.pushButton_4 = QPushButton(self.buttons_frame)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setMinimumSize(QSize(0, 0))
        self.pushButton_4.setMaximumSize(QSize(250, 45))
        self.pushButton_4.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_4.setAutoFillBackground(False)
        self.pushButton_4.setStyleSheet(u"background-color: rgb(18, 14, 57); border: none; color: white;")
        icon = QIcon()
        icon.addFile(u"images/camera.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_4.setIcon(icon)
        self.pushButton_4.setIconSize(QSize(22, 22))

        self.horizontalLayout_5.addWidget(self.pushButton_4)

        self.pushButton_3 = QPushButton(self.buttons_frame)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setMinimumSize(QSize(0, 0))
        self.pushButton_3.setMaximumSize(QSize(250, 45))
        self.pushButton_3.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_3.setAutoFillBackground(False)
        self.pushButton_3.setStyleSheet(u"background-color: rgb(18, 14, 57); border: none; color: white;")
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setIconSize(QSize(22, 22))

        self.horizontalLayout_5.addWidget(self.pushButton_3)

        self.pushButton_5 = QPushButton(self.buttons_frame)
        self.pushButton_5.setObjectName(u"pushButton_5")
        sizePolicy1 = QSizePolicy(QSizePolicy.Maximum, QSizePolicy.Minimum)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy1)
        self.pushButton_5.setMinimumSize(QSize(0, 0))
        self.pushButton_5.setMaximumSize(QSize(250, 45))
        self.pushButton_5.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_5.setAutoFillBackground(False)
        self.pushButton_5.setStyleSheet(u"background-color: rgb(18, 14, 57); border: none; color: white;")
        icon1 = QIcon()
        icon1.addFile(u"images/kontroller.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_5.setIcon(icon1)
        self.pushButton_5.setIconSize(QSize(22, 22))

        self.horizontalLayout_5.addWidget(self.pushButton_5)

        self.pushButton_6 = QPushButton(self.buttons_frame)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setMinimumSize(QSize(0, 0))
        self.pushButton_6.setMaximumSize(QSize(250, 45))
        self.pushButton_6.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_6.setAutoFillBackground(False)
        self.pushButton_6.setStyleSheet(u"background-color: rgb(18, 14, 57); border: none; color: white;")
        self.pushButton_6.setIconSize(QSize(22, 22))

        self.horizontalLayout_5.addWidget(self.pushButton_6)


        self.gridLayout_2.addWidget(self.buttons_frame, 0, 1, 1, 1)

        self.logo_frame = QFrame(self.title_bar)
        self.logo_frame.setObjectName(u"logo_frame")
        self.logo_frame.setMinimumSize(QSize(0, 0))
        self.logo_frame.setMaximumSize(QSize(16777215, 16777215))
        self.logo_frame.setStyleSheet(u"")
        self.logo_frame.setFrameShape(QFrame.NoFrame)
        self.logo_frame.setFrameShadow(QFrame.Raised)
        self.horizontalLayout = QHBoxLayout(self.logo_frame)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.frame_9 = QFrame(self.logo_frame)
        self.frame_9.setObjectName(u"frame_9")
        self.frame_9.setMaximumSize(QSize(16777215, 16777215))
        self.frame_9.setFrameShape(QFrame.NoFrame)
        self.frame_9.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_3 = QHBoxLayout(self.frame_9)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.label = QLabel(self.frame_9)
        self.label.setObjectName(u"label")
        self.label.setEnabled(True)
        self.label.setMinimumSize(QSize(0, 0))
        self.label.setMaximumSize(QSize(26, 26))
        self.label.setSizeIncrement(QSize(100, 100))
        self.label.setBaseSize(QSize(100, 100))
        self.label.setTextFormat(Qt.AutoText)
        self.label.setPixmap(QPixmap(u"images/logo.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(Qt.AlignCenter)
        self.label.setIndent(0)

        self.horizontalLayout_3.addWidget(self.label)

        self.label_title_2 = QLabel(self.frame_9)
        self.label_title_2.setObjectName(u"label_title_2")
        self.label_title_2.setEnabled(True)
        self.label_title_2.setMaximumSize(QSize(16777215, 16777215))
        self.label_title_2.setStyleSheet(u"color: white;")
        self.label_title_2.setScaledContents(False)

        self.horizontalLayout_3.addWidget(self.label_title_2)


        self.horizontalLayout.addWidget(self.frame_9)


        self.gridLayout_2.addWidget(self.logo_frame, 0, 0, 1, 1)


        self.verticalLayout.addWidget(self.title_bar)

        self.content_bar = QFrame(self.drop_shadow_frame)
        self.content_bar.setObjectName(u"content_bar")
        self.content_bar.setMinimumSize(QSize(0, 0))
        self.content_bar.setMaximumSize(QSize(16777215, 16777215))
        self.content_bar.setStyleSheet(u"background-color: none; color: white;\n"
"QPushButton { background-color: grey; color: red; }")
        self.content_bar.setFrameShape(QFrame.NoFrame)
        self.content_bar.setFrameShadow(QFrame.Raised)
        self.gridLayout_12 = QGridLayout(self.content_bar)
        self.gridLayout_12.setObjectName(u"gridLayout_12")
        self.stackedWidget = QStackedWidget(self.content_bar)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setFrameShadow(QFrame.Plain)
        self.kontroller = QWidget()
        self.kontroller.setObjectName(u"kontroller")
        self.gridLayout_14 = QGridLayout(self.kontroller)
        self.gridLayout_14.setObjectName(u"gridLayout_14")
        self.frame_12 = QFrame(self.kontroller)
        self.frame_12.setObjectName(u"frame_12")
        self.frame_12.setStyleSheet(u"#frame_14 {background-color:  rgba(0, 0, 0, 30);}")
        self.frame_12.setFrameShape(QFrame.NoFrame)
        self.frame_12.setFrameShadow(QFrame.Raised)
        self.frame_14 = QFrame(self.frame_12)
        self.frame_14.setObjectName(u"frame_14")
        self.frame_14.setGeometry(QRect(120, 90, 1001, 741))
        self.frame_14.setFrameShape(QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QFrame.Raised)
        self.label_3 = QLabel(self.frame_14)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(110, 20, 341, 51))
        font1 = QFont()
        font1.setFamily(u"Arial")
        font1.setPointSize(16)
        self.label_3.setFont(font1)
        self.label_4 = QLabel(self.frame_14)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(300, 270, 461, 301))
        self.label_4.setPixmap(QPixmap(u"images/xbox360.png"))
        self.label_4.setScaledContents(True)

        self.gridLayout_14.addWidget(self.frame_12, 0, 0, 1, 1)

        self.stackedWidget.addWidget(self.kontroller)
        self.informasjon = QWidget()
        self.informasjon.setObjectName(u"informasjon")
        self.gridLayout_13 = QGridLayout(self.informasjon)
        self.gridLayout_13.setSpacing(0)
        self.gridLayout_13.setObjectName(u"gridLayout_13")
        self.gridLayout_13.setContentsMargins(0, -1, -1, -1)
        self.frame = QFrame(self.informasjon)
        self.frame.setObjectName(u"frame")
        self.frame.setEnabled(True)
        self.frame.setMinimumSize(QSize(0, 0))
        self.frame.setMaximumSize(QSize(16777215, 16777215))
        self.frame.setBaseSize(QSize(0, 0))
        self.frame.setToolTipDuration(4)
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet(u"QPushButton{background-color: grey; color: white;} #container5 {background-color:  rgba(0, 0, 0, 30);}#container6 {background-color:  rgba(0, 0, 0, 30);} #container7 {background-color:  rgba(0, 0, 0, 30);}  #container10 {background-color:  rgba(0, 0, 0, 30);}")
        self.frame.setFrameShape(QFrame.NoFrame)
        self.frame.setFrameShadow(QFrame.Raised)
        self.gridLayout_6 = QGridLayout(self.frame)
        self.gridLayout_6.setObjectName(u"gridLayout_6")
        self.gridLayout_6.setHorizontalSpacing(0)
        self.gridLayout_6.setVerticalSpacing(-1)
        self.gridLayout_6.setContentsMargins(0, -1, 0, 0)
        self.container7 = QFrame(self.frame)
        self.container7.setObjectName(u"container7")
        self.container7.setMaximumSize(QSize(16777215, 16777215))
        self.container7.setAutoFillBackground(False)
        self.container7.setStyleSheet(u"QPushButton{background-color: grey; color: white;}")
        self.container7.setFrameShape(QFrame.NoFrame)
        self.container7.setFrameShadow(QFrame.Raised)
        self.mainpulator = QLabel(self.container7)
        self.mainpulator.setObjectName(u"mainpulator")
        self.mainpulator.setGeometry(QRect(12, 12, 115, 19))
        self.mainpulator.setMaximumSize(QSize(1000, 50))
        self.mainpulator.setFont(font1)
        self.mainpulator.setTextFormat(Qt.RichText)
        self.frame_4 = QFrame(self.container7)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(12, 78, 420, 171))
        self.frame_4.setMinimumSize(QSize(0, 0))
        self.frame_4.setMaximumSize(QSize(16777215, 16777215))
        self.frame_4.setFrameShape(QFrame.NoFrame)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.label_19 = QLabel(self.frame_4)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(10, -10, 350, 171))
        self.label_19.setMinimumSize(QSize(350, 100))
        self.label_19.setMaximumSize(QSize(16777215, 16777215))
        self.label_19.setSizeIncrement(QSize(0, 0))
        self.label_19.setPixmap(QPixmap(u"images/manipulator.png"))
        self.label_19.setScaledContents(True)
        self.circularProgressBarBase_12 = QFrame(self.container7)
        self.circularProgressBarBase_12.setObjectName(u"circularProgressBarBase_12")
        self.circularProgressBarBase_12.setGeometry(QRect(210, 170, 70, 70))
        self.circularProgressBarBase_12.setFrameShape(QFrame.NoFrame)
        self.circularProgressBarBase_12.setFrameShadow(QFrame.Raised)
        self.circularProgress_21 = QFrame(self.circularProgressBarBase_12)
        self.circularProgress_21.setObjectName(u"circularProgress_21")
        self.circularProgress_21.setGeometry(QRect(5, 5, 60, 60))
        self.circularProgress_21.setStyleSheet(u"QFrame { border-radius: 30px; background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.999 rgba(255, 0, 127, 0), stop:1.0 rgba(85, 170, 255, 255)); }")
        self.circularProgress_21.setFrameShape(QFrame.NoFrame)
        self.circularProgress_21.setFrameShadow(QFrame.Raised)
        self.circularBg_20 = QFrame(self.circularProgressBarBase_12)
        self.circularBg_20.setObjectName(u"circularBg_20")
        self.circularBg_20.setGeometry(QRect(5, 5, 60, 60))
        self.circularBg_20.setStyleSheet(u"QFrame { border-radius: 30px; background-color: rgba(77, 77, 127, 100); }")
        self.circularBg_20.setFrameShape(QFrame.NoFrame)
        self.circularBg_20.setFrameShadow(QFrame.Raised)
        self.container_20 = QFrame(self.circularProgressBarBase_12)
        self.container_20.setObjectName(u"container_20")
        self.container_20.setGeometry(QRect(10, 10, 50, 50))
        self.container_20.setStyleSheet(u"QFrame { border-radius: 25px; background-color: rgba(77, 77, 127, 255); }")
        self.container_20.setFrameShape(QFrame.StyledPanel)
        self.container_20.setFrameShadow(QFrame.Raised)
        self.labelPercentage_22 = QLabel(self.container_20)
        self.labelPercentage_22.setObjectName(u"labelPercentage_22")
        self.labelPercentage_22.setGeometry(QRect(10, 13, 31, 21))
        font2 = QFont()
        font2.setFamily(u"Arial")
        font2.setPointSize(10)
        self.labelPercentage_22.setFont(font2)
        self.labelPercentage_22.setScaledContents(False)
        self.labelPercentage_22.setAlignment(Qt.AlignCenter)
        self.labelPercentage_22.setWordWrap(False)
        self.circularProgressBarBase_13 = QFrame(self.container7)
        self.circularProgressBarBase_13.setObjectName(u"circularProgressBarBase_13")
        self.circularProgressBarBase_13.setGeometry(QRect(150, 70, 70, 70))
        self.circularProgressBarBase_13.setFrameShape(QFrame.NoFrame)
        self.circularProgressBarBase_13.setFrameShadow(QFrame.Raised)
        self.circularProgress_22 = QFrame(self.circularProgressBarBase_13)
        self.circularProgress_22.setObjectName(u"circularProgress_22")
        self.circularProgress_22.setGeometry(QRect(5, 5, 60, 60))
        self.circularProgress_22.setStyleSheet(u"QFrame { border-radius: 30px; background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.999 rgba(255, 0, 127, 0), stop:1.0 rgba(85, 170, 255, 255)); }")
        self.circularProgress_22.setFrameShape(QFrame.NoFrame)
        self.circularProgress_22.setFrameShadow(QFrame.Raised)
        self.circularBg_21 = QFrame(self.circularProgressBarBase_13)
        self.circularBg_21.setObjectName(u"circularBg_21")
        self.circularBg_21.setGeometry(QRect(5, 5, 60, 60))
        self.circularBg_21.setStyleSheet(u"QFrame { border-radius: 30px; background-color: rgba(77, 77, 127, 100); }")
        self.circularBg_21.setFrameShape(QFrame.NoFrame)
        self.circularBg_21.setFrameShadow(QFrame.Raised)
        self.container_21 = QFrame(self.circularProgressBarBase_13)
        self.container_21.setObjectName(u"container_21")
        self.container_21.setGeometry(QRect(10, 10, 50, 50))
        self.container_21.setStyleSheet(u"QFrame { border-radius: 25px; background-color: rgba(77, 77, 127, 255); }")
        self.container_21.setFrameShape(QFrame.StyledPanel)
        self.container_21.setFrameShadow(QFrame.Raised)
        self.labelPercentage_23 = QLabel(self.container_21)
        self.labelPercentage_23.setObjectName(u"labelPercentage_23")
        self.labelPercentage_23.setGeometry(QRect(10, 13, 31, 21))
        self.labelPercentage_23.setFont(font2)
        self.labelPercentage_23.setScaledContents(False)
        self.labelPercentage_23.setAlignment(Qt.AlignCenter)
        self.labelPercentage_23.setWordWrap(False)
        self.circularProgressBarBase_14 = QFrame(self.container7)
        self.circularProgressBarBase_14.setObjectName(u"circularProgressBarBase_14")
        self.circularProgressBarBase_14.setGeometry(QRect(40, 160, 70, 70))
        self.circularProgressBarBase_14.setFrameShape(QFrame.NoFrame)
        self.circularProgressBarBase_14.setFrameShadow(QFrame.Raised)
        self.circularProgress_24 = QFrame(self.circularProgressBarBase_14)
        self.circularProgress_24.setObjectName(u"circularProgress_24")
        self.circularProgress_24.setGeometry(QRect(5, 5, 60, 60))
        self.circularProgress_24.setStyleSheet(u"QFrame { border-radius: 30px; background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.999 rgba(255, 0, 127, 0), stop:1.0 rgba(85, 170, 255, 255)); }")
        self.circularProgress_24.setFrameShape(QFrame.NoFrame)
        self.circularProgress_24.setFrameShadow(QFrame.Raised)
        self.circularBg_23 = QFrame(self.circularProgressBarBase_14)
        self.circularBg_23.setObjectName(u"circularBg_23")
        self.circularBg_23.setGeometry(QRect(5, 5, 60, 60))
        self.circularBg_23.setStyleSheet(u"QFrame { border-radius: 30px; background-color: rgba(77, 77, 127, 100); }")
        self.circularBg_23.setFrameShape(QFrame.NoFrame)
        self.circularBg_23.setFrameShadow(QFrame.Raised)
        self.container_23 = QFrame(self.circularProgressBarBase_14)
        self.container_23.setObjectName(u"container_23")
        self.container_23.setGeometry(QRect(10, 10, 50, 50))
        self.container_23.setStyleSheet(u"QFrame { border-radius: 25px; background-color: rgba(77, 77, 127, 255); }")
        self.container_23.setFrameShape(QFrame.StyledPanel)
        self.container_23.setFrameShadow(QFrame.Raised)
        self.labelPercentage_25 = QLabel(self.container_23)
        self.labelPercentage_25.setObjectName(u"labelPercentage_25")
        self.labelPercentage_25.setGeometry(QRect(10, 13, 31, 21))
        self.labelPercentage_25.setFont(font2)
        self.labelPercentage_25.setScaledContents(False)
        self.labelPercentage_25.setAlignment(Qt.AlignCenter)
        self.labelPercentage_25.setWordWrap(False)
        self.frame_4.raise_()
        self.mainpulator.raise_()
        self.circularProgressBarBase_12.raise_()
        self.circularProgressBarBase_13.raise_()
        self.circularProgressBarBase_14.raise_()

        self.gridLayout_6.addWidget(self.container7, 1, 0, 1, 1)

        self.container5 = QFrame(self.frame)
        self.container5.setObjectName(u"container5")
        self.container5.setMinimumSize(QSize(0, 0))
        self.container5.setMaximumSize(QSize(16777215, 16777213))
        self.container5.setAutoFillBackground(False)
        self.container5.setStyleSheet(u"QPushButton{background-color: grey; color: white;}")
        self.container5.setFrameShape(QFrame.NoFrame)
        self.container5.setFrameShadow(QFrame.Raised)
        self.verticalLayout_9 = QVBoxLayout(self.container5)
        self.verticalLayout_9.setObjectName(u"verticalLayout_9")
        self.bildebehandling = QLabel(self.container5)
        self.bildebehandling.setObjectName(u"bildebehandling")
        self.bildebehandling.setMinimumSize(QSize(0, 0))
        self.bildebehandling.setMaximumSize(QSize(16777215, 16777215))
        self.bildebehandling.setFont(font1)
        self.bildebehandling.setTextFormat(Qt.RichText)

        self.verticalLayout_9.addWidget(self.bildebehandling)

        self.container_bilde = QFrame(self.container5)
        self.container_bilde.setObjectName(u"container_bilde")
        self.container_bilde.setMaximumSize(QSize(16777215, 16777215))
        self.container_bilde.setFrameShape(QFrame.NoFrame)
        self.container_bilde.setFrameShadow(QFrame.Raised)
        self.gridLayout_11 = QGridLayout(self.container_bilde)
        self.gridLayout_11.setObjectName(u"gridLayout_11")
        self.btn_korallrev = QPushButton(self.container_bilde)
        self.btn_korallrev.setObjectName(u"btn_korallrev")
        self.btn_korallrev.setMinimumSize(QSize(0, 30))
        self.btn_korallrev.setFont(font)
        self.btn_korallrev.setStyleSheet(u"background-color: rgb(92, 114, 194);")

        self.gridLayout_11.addWidget(self.btn_korallrev, 1, 0, 1, 1)

        self.label_bilde2 = QLabel(self.container_bilde)
        self.label_bilde2.setObjectName(u"label_bilde2")
        self.label_bilde2.setMaximumSize(QSize(16777215, 16777215))
        self.label_bilde2.setFont(font)
        self.label_bilde2.setTextFormat(Qt.PlainText)

        self.gridLayout_11.addWidget(self.label_bilde2, 1, 1, 1, 1)

        self.label_bilde1 = QLabel(self.container_bilde)
        self.label_bilde1.setObjectName(u"label_bilde1")
        self.label_bilde1.setMinimumSize(QSize(0, 0))
        self.label_bilde1.setMaximumSize(QSize(16777215, 16777215))
        self.label_bilde1.setFont(font)
        self.label_bilde1.setFrameShadow(QFrame.Plain)
        self.label_bilde1.setTextFormat(Qt.PlainText)

        self.gridLayout_11.addWidget(self.label_bilde1, 0, 1, 1, 1)

        self.label_bilde3 = QLabel(self.container_bilde)
        self.label_bilde3.setObjectName(u"label_bilde3")
        self.label_bilde3.setMaximumSize(QSize(16777215, 16777215))
        self.label_bilde3.setFont(font)
        self.label_bilde3.setTextFormat(Qt.PlainText)
        self.label_bilde3.setWordWrap(False)

        self.gridLayout_11.addWidget(self.label_bilde3, 2, 1, 1, 1)

        self.btn_fotomoasaikk = QPushButton(self.container_bilde)
        self.btn_fotomoasaikk.setObjectName(u"btn_fotomoasaikk")
        self.btn_fotomoasaikk.setMinimumSize(QSize(0, 30))
        self.btn_fotomoasaikk.setFont(font)
        self.btn_fotomoasaikk.setStyleSheet(u"background-color: rgb(92, 114, 194);")

        self.gridLayout_11.addWidget(self.btn_fotomoasaikk, 2, 0, 1, 1)

        self.btn_havbunn = QPushButton(self.container_bilde)
        self.btn_havbunn.setObjectName(u"btn_havbunn")
        self.btn_havbunn.setMinimumSize(QSize(0, 30))
        self.btn_havbunn.setFont(font)
        self.btn_havbunn.setStyleSheet(u"background-color: rgb(92, 114, 194);")

        self.gridLayout_11.addWidget(self.btn_havbunn, 0, 0, 1, 1)


        self.verticalLayout_9.addWidget(self.container_bilde)


        self.gridLayout_6.addWidget(self.container5, 0, 0, 1, 1)

        self.container10 = QFrame(self.frame)
        self.container10.setObjectName(u"container10")
        self.container10.setMaximumSize(QSize(16777215, 16777215))
        self.container10.setFrameShape(QFrame.NoFrame)
        self.container10.setFrameShadow(QFrame.Raised)
        self.circularProgressBarBase = QWidget(self.container10)
        self.circularProgressBarBase.setObjectName(u"circularProgressBarBase")
        self.circularProgressBarBase.setGeometry(QRect(70, 40, 70, 70))
        self.circularProgress = QFrame(self.circularProgressBarBase)
        self.circularProgress.setObjectName(u"circularProgress")
        self.circularProgress.setGeometry(QRect(5, 5, 60, 60))
        self.circularProgress.setStyleSheet(u"QFrame { border-radius: 30px; background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.999 rgba(255, 0, 127, 0), stop:1.0 rgba(85, 170, 255, 255)); }")
        self.circularProgress.setFrameShape(QFrame.NoFrame)
        self.circularProgress.setFrameShadow(QFrame.Raised)
        self.circularBg = QFrame(self.circularProgressBarBase)
        self.circularBg.setObjectName(u"circularBg")
        self.circularBg.setGeometry(QRect(5, 5, 60, 60))
        self.circularBg.setStyleSheet(u"QFrame { border-radius: 30px; background-color: rgba(77, 77, 127, 100); }")
        self.circularBg.setFrameShape(QFrame.NoFrame)
        self.circularBg.setFrameShadow(QFrame.Raised)
        self.container = QFrame(self.circularProgressBarBase)
        self.container.setObjectName(u"container")
        self.container.setGeometry(QRect(10, 10, 50, 50))
        self.container.setStyleSheet(u"QFrame { border-radius: 25px; background-color: rgba(77, 77, 127, 255); }")
        self.container.setFrameShape(QFrame.StyledPanel)
        self.container.setFrameShadow(QFrame.Raised)
        self.labelPercentage = QLabel(self.container)
        self.labelPercentage.setObjectName(u"labelPercentage")
        self.labelPercentage.setGeometry(QRect(10, 13, 31, 21))
        self.labelPercentage.setFont(font2)
        self.labelPercentage.setScaledContents(False)
        self.labelPercentage.setAlignment(Qt.AlignCenter)
        self.labelPercentage.setWordWrap(False)
        self.circularBg.raise_()
        self.circularProgress.raise_()
        self.container.raise_()
        self.slider = QSlider(self.container10)
        self.slider.setObjectName(u"slider")
        self.slider.setGeometry(QRect(30, 130, 160, 22))
        self.slider.setMinimum(-100)
        self.slider.setMaximum(100)
        self.slider.setOrientation(Qt.Horizontal)

        self.gridLayout_6.addWidget(self.container10, 2, 0, 1, 1)


        self.gridLayout_13.addWidget(self.frame, 0, 1, 1, 1)

        self.frame_2 = QFrame(self.informasjon)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setMinimumSize(QSize(0, 0))
        self.frame_2.setMaximumSize(QSize(16777215, 16777215))
        self.frame_2.setStyleSheet(u"#container3 { background-color:  rgba(0, 0, 0, 30);} #container4 { background-color:  rgba(0, 0, 0, 30);}  #container6 { background-color:  rgba(0, 0, 0, 30);}")
        self.frame_2.setFrameShape(QFrame.NoFrame)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.verticalLayout_11 = QVBoxLayout(self.frame_2)
        self.verticalLayout_11.setSpacing(10)
        self.verticalLayout_11.setObjectName(u"verticalLayout_11")
        self.verticalLayout_11.setContentsMargins(10, 10, 10, 10)
        self.frame_7 = QFrame(self.frame_2)
        self.frame_7.setObjectName(u"frame_7")
        self.frame_7.setMaximumSize(QSize(16777215, 250))
        self.frame_7.setAutoFillBackground(False)
        self.frame_7.setStyleSheet(u"QPushButton{background-color: grey; color: white;} #container1 {background-color:  rgba(0, 0, 0, 30);} #container2 {background-color:  rgba(0, 0, 0, 30);} #container9 {background-color:  rgba(0, 0, 0, 30);} ")
        self.frame_7.setFrameShape(QFrame.NoFrame)
        self.gridLayout = QGridLayout(self.frame_7)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setHorizontalSpacing(-1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.container9 = QFrame(self.frame_7)
        self.container9.setObjectName(u"container9")
        self.container9.setMaximumSize(QSize(16777215, 16777215))
        self.container9.setFrameShape(QFrame.StyledPanel)
        self.container9.setFrameShadow(QFrame.Raised)
        self.gridLayout_9 = QGridLayout(self.container9)
        self.gridLayout_9.setObjectName(u"gridLayout_9")
        self.frame_11 = QFrame(self.container9)
        self.frame_11.setObjectName(u"frame_11")
        self.frame_11.setMaximumSize(QSize(16777215, 16777215))
        self.frame_11.setFrameShape(QFrame.NoFrame)
        self.frame_11.setFrameShadow(QFrame.Raised)
        self.verticalLayout_14 = QVBoxLayout(self.frame_11)
        self.verticalLayout_14.setObjectName(u"verticalLayout_14")
        self.kamera_6 = QLabel(self.frame_11)
        self.kamera_6.setObjectName(u"kamera_6")
        self.kamera_6.setMinimumSize(QSize(200, 50))
        self.kamera_6.setMaximumSize(QSize(16777215, 16777215))
        self.kamera_6.setBaseSize(QSize(200, 0))
        self.kamera_6.setFont(font1)
        self.kamera_6.setStyleSheet(u"background-color: none; font-size: 1en;")
        self.kamera_6.setTextFormat(Qt.RichText)
        self.kamera_6.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.kamera_6.setMargin(10)

        self.verticalLayout_14.addWidget(self.kamera_6)

        self.frame_13 = QFrame(self.frame_11)
        self.frame_13.setObjectName(u"frame_13")
        self.frame_13.setMaximumSize(QSize(16777215, 16777215))
        self.frame_13.setStyleSheet(u"QFrame{ background-color: none;}")
        self.frame_13.setFrameShape(QFrame.NoFrame)
        self.frame_13.setFrameShadow(QFrame.Plain)
        self.frame_13.setLineWidth(0)
        self.verticalLayout_6 = QVBoxLayout(self.frame_13)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.btn_frontkamera = QPushButton(self.frame_13)
        self.btn_frontkamera.setObjectName(u"btn_frontkamera")
        self.btn_frontkamera.setMaximumSize(QSize(16777215, 40))
        self.btn_frontkamera.setFont(font)
        self.btn_frontkamera.setStyleSheet(u"background-color: rgb(92, 114, 194);")

        self.verticalLayout_6.addWidget(self.btn_frontkamera)

        self.btn_havbunnskamera = QPushButton(self.frame_13)
        self.btn_havbunnskamera.setObjectName(u"btn_havbunnskamera")
        self.btn_havbunnskamera.setMaximumSize(QSize(16777215, 40))
        self.btn_havbunnskamera.setFont(font)
        self.btn_havbunnskamera.setStyleSheet(u"background-color: rgb(92, 114, 194);")

        self.verticalLayout_6.addWidget(self.btn_havbunnskamera)

        self.btn_slettsistebilde = QPushButton(self.frame_13)
        self.btn_slettsistebilde.setObjectName(u"btn_slettsistebilde")
        self.btn_slettsistebilde.setMaximumSize(QSize(16777215, 40))
        self.btn_slettsistebilde.setFont(font)
        self.btn_slettsistebilde.setStyleSheet(u"background-color: rgb(92, 114, 194);")

        self.verticalLayout_6.addWidget(self.btn_slettsistebilde)


        self.verticalLayout_14.addWidget(self.frame_13)


        self.gridLayout_9.addWidget(self.frame_11, 0, 0, 1, 1)


        self.gridLayout.addWidget(self.container9, 0, 1, 1, 1)

        self.container1 = QFrame(self.frame_7)
        self.container1.setObjectName(u"container1")
        self.container1.setMaximumSize(QSize(400, 16777215))
        self.container1.setStyleSheet(u"QPushButton{background-color: grey; color: white;}")
        self.container1.setFrameShape(QFrame.NoFrame)
        self.container1.setFrameShadow(QFrame.Raised)
        self.container1.setLineWidth(0)
        self.verticalLayout_5 = QVBoxLayout(self.container1)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.verticalLayout_5.setContentsMargins(10, 10, 10, 10)
        self.label_2 = QLabel(self.container1)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setMaximumSize(QSize(16777215, 16777215))
        self.label_2.setPixmap(QPixmap(u"images/eksempelbilde.png"))
        self.label_2.setScaledContents(True)

        self.verticalLayout_5.addWidget(self.label_2)


        self.gridLayout.addWidget(self.container1, 0, 2, 1, 1)

        self.container2 = QFrame(self.frame_7)
        self.container2.setObjectName(u"container2")
        self.container2.setMaximumSize(QSize(16777215, 16777215))
        self.container2.setAutoFillBackground(False)
        self.container2.setStyleSheet(u"QPushButton{background-color: grey; color: white;}")
        self.container2.setFrameShape(QFrame.NoFrame)
        self.container2.setFrameShadow(QFrame.Raised)
        self.verticalLayout_8 = QVBoxLayout(self.container2)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.frame_10 = QFrame(self.container2)
        self.frame_10.setObjectName(u"frame_10")
        self.frame_10.setMinimumSize(QSize(0, 0))
        self.frame_10.setMaximumSize(QSize(16777215, 16777215))
        self.frame_10.setFrameShape(QFrame.NoFrame)
        self.frame_10.setFrameShadow(QFrame.Raised)
        self.verticalLayout_13 = QVBoxLayout(self.frame_10)
        self.verticalLayout_13.setObjectName(u"verticalLayout_13")
        self.kontroller_7 = QLabel(self.frame_10)
        self.kontroller_7.setObjectName(u"kontroller_7")
        self.kontroller_7.setMinimumSize(QSize(0, 50))
        self.kontroller_7.setMaximumSize(QSize(16777215, 16777215))
        self.kontroller_7.setFont(font1)
        self.kontroller_7.setStyleSheet(u"background-color: none;")
        self.kontroller_7.setTextFormat(Qt.PlainText)

        self.verticalLayout_13.addWidget(self.kontroller_7)

        self.frame_8 = QFrame(self.frame_10)
        self.frame_8.setObjectName(u"frame_8")
        self.frame_8.setMinimumSize(QSize(0, 0))
        self.frame_8.setMaximumSize(QSize(16777215, 16777215))
        self.frame_8.setFrameShape(QFrame.NoFrame)
        self.frame_8.setFrameShadow(QFrame.Raised)
        self.verticalLayout_4 = QVBoxLayout(self.frame_8)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.btn_manuell = QPushButton(self.frame_8)
        self.btn_manuell.setObjectName(u"btn_manuell")
        self.btn_manuell.setMaximumSize(QSize(16777215, 16777215))
        self.btn_manuell.setFont(font)
        self.btn_manuell.setStyleSheet(u"background-color: rgb(92, 114, 194);")

        self.verticalLayout_4.addWidget(self.btn_manuell)

        self.btn_auto = QPushButton(self.frame_8)
        self.btn_auto.setObjectName(u"btn_auto")
        self.btn_auto.setMaximumSize(QSize(16777215, 16777215))
        self.btn_auto.setFont(font)
        self.btn_auto.setStyleSheet(u"background-color: rgb(92, 114, 194);")

        self.verticalLayout_4.addWidget(self.btn_auto)


        self.verticalLayout_13.addWidget(self.frame_8)


        self.verticalLayout_8.addWidget(self.frame_10)


        self.gridLayout.addWidget(self.container2, 0, 0, 1, 1)


        self.verticalLayout_11.addWidget(self.frame_7)

        self.frame_6 = QFrame(self.frame_2)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setFrameShape(QFrame.NoFrame)
        self.frame_6.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_4 = QHBoxLayout(self.frame_6)
#ifndef Q_OS_MAC
        self.horizontalLayout_4.setSpacing(-1)
#endif
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.container3 = QFrame(self.frame_6)
        self.container3.setObjectName(u"container3")
        self.container3.setMinimumSize(QSize(0, 0))
        self.container3.setMaximumSize(QSize(16777215, 16777215))
        self.container3.setAutoFillBackground(False)
        self.container3.setStyleSheet(u"QPushButton{background-color: grey; color: white;}\n"
" #container3 {background-color:  rgba(0, 0, 0, 30);}")
        self.container3.setFrameShape(QFrame.NoFrame)
        self.container3.setFrameShadow(QFrame.Raised)
        self.frame_17 = QFrame(self.container3)
        self.frame_17.setObjectName(u"frame_17")
        self.frame_17.setGeometry(QRect(12, 60, 300, 280))
        self.frame_17.setMinimumSize(QSize(0, 0))
        self.frame_17.setMaximumSize(QSize(16777215, 16777215))
        self.frame_17.setFrameShape(QFrame.NoFrame)
        self.frame_17.setFrameShadow(QFrame.Raised)
        self.gridLayout_8 = QGridLayout(self.frame_17)
        self.gridLayout_8.setObjectName(u"gridLayout_8")
        self.label_spenning = QLabel(self.frame_17)
        self.label_spenning.setObjectName(u"label_spenning")
        self.label_spenning.setFont(font)
        self.label_spenning.setTextFormat(Qt.RichText)

        self.gridLayout_8.addWidget(self.label_spenning, 2, 0, 1, 1)

        self.temp_vann = QLabel(self.frame_17)
        self.temp_vann.setObjectName(u"temp_vann")
        self.temp_vann.setFont(font)
        self.temp_vann.setStyleSheet(u"background-color: grey; border-radius: 5px;")
        self.temp_vann.setAlignment(Qt.AlignCenter)

        self.gridLayout_8.addWidget(self.temp_vann, 6, 1, 1, 1)

        self.label_temp_vann = QLabel(self.frame_17)
        self.label_temp_vann.setObjectName(u"label_temp_vann")
        self.label_temp_vann.setFont(font)
        self.label_temp_vann.setTextFormat(Qt.PlainText)

        self.gridLayout_8.addWidget(self.label_temp_vann, 6, 0, 1, 1)

        self.label_tid = QLabel(self.frame_17)
        self.label_tid.setObjectName(u"label_tid")
        self.label_tid.setFont(font)
        self.label_tid.setTextFormat(Qt.RichText)

        self.gridLayout_8.addWidget(self.label_tid, 0, 0, 1, 1)

        self.tid = QLabel(self.frame_17)
        self.tid.setObjectName(u"tid")
        self.tid.setFont(font)
        self.tid.setStyleSheet(u"background-color: grey; border-radius: 5px;")
        self.tid.setAlignment(Qt.AlignCenter)

        self.gridLayout_8.addWidget(self.tid, 0, 1, 1, 1)

        self.label_dybde = QLabel(self.frame_17)
        self.label_dybde.setObjectName(u"label_dybde")
        self.label_dybde.setFont(font)
        self.label_dybde.setTextFormat(Qt.RichText)

        self.gridLayout_8.addWidget(self.label_dybde, 1, 0, 1, 1)

        self.spenning = QLabel(self.frame_17)
        self.spenning.setObjectName(u"spenning")
        self.spenning.setFont(font)
        self.spenning.setStyleSheet(u"background-color: grey; border-radius: 5px;")
        self.spenning.setAlignment(Qt.AlignCenter)

        self.gridLayout_8.addWidget(self.spenning, 2, 1, 1, 1)

        self.label_orientering = QLabel(self.frame_17)
        self.label_orientering.setObjectName(u"label_orientering")
        self.label_orientering.setFont(font)
        self.label_orientering.setTextFormat(Qt.PlainText)

        self.gridLayout_8.addWidget(self.label_orientering, 5, 0, 1, 1)

        self.strom2 = QLabel(self.frame_17)
        self.strom2.setObjectName(u"strom2")
        self.strom2.setFont(font)
        self.strom2.setStyleSheet(u"background-color: grey; border-radius: 5px;")
        self.strom2.setAlignment(Qt.AlignCenter)

        self.gridLayout_8.addWidget(self.strom2, 4, 1, 1, 1)

        self.label_strom1 = QLabel(self.frame_17)
        self.label_strom1.setObjectName(u"label_strom1")
        self.label_strom1.setFont(font)
        self.label_strom1.setTextFormat(Qt.PlainText)

        self.gridLayout_8.addWidget(self.label_strom1, 3, 0, 1, 1)

        self.label_strom = QLabel(self.frame_17)
        self.label_strom.setObjectName(u"label_strom")
        self.label_strom.setFont(font)
        self.label_strom.setTextFormat(Qt.RichText)

        self.gridLayout_8.addWidget(self.label_strom, 4, 0, 1, 1)

        self.dybde = QLabel(self.frame_17)
        self.dybde.setObjectName(u"dybde")
        self.dybde.setFont(font)
        self.dybde.setStyleSheet(u"background-color: grey; border-radius: 5px;")
        self.dybde.setAlignment(Qt.AlignCenter)

        self.gridLayout_8.addWidget(self.dybde, 1, 1, 1, 1)

        self.orientering = QLabel(self.frame_17)
        self.orientering.setObjectName(u"orientering")
        self.orientering.setFont(font)
        self.orientering.setStyleSheet(u"background-color: grey; border-radius: 5px;")
        self.orientering.setAlignment(Qt.AlignCenter)

        self.gridLayout_8.addWidget(self.orientering, 5, 1, 1, 1)

        self.strom1 = QLabel(self.frame_17)
        self.strom1.setObjectName(u"strom1")
        self.strom1.setFont(font)
        self.strom1.setStyleSheet(u"background-color: grey; border-radius: 5px;")
        self.strom1.setAlignment(Qt.AlignCenter)

        self.gridLayout_8.addWidget(self.strom1, 3, 1, 1, 1)

        self.frame_19 = QFrame(self.container3)
        self.frame_19.setObjectName(u"frame_19")
        self.frame_19.setGeometry(QRect(330, 160, 300, 160))
        self.frame_19.setMinimumSize(QSize(0, 0))
        self.frame_19.setMaximumSize(QSize(16777215, 16777215))
        self.frame_19.setFrameShape(QFrame.NoFrame)
        self.frame_19.setFrameShadow(QFrame.Raised)
        self.gridLayout_10 = QGridLayout(self.frame_19)
        self.gridLayout_10.setObjectName(u"gridLayout_10")
        self.frame_16 = QFrame(self.frame_19)
        self.frame_16.setObjectName(u"frame_16")
        self.frame_16.setMaximumSize(QSize(16777215, 16777215))
        self.frame_16.setFrameShape(QFrame.NoFrame)
        self.frame_16.setFrameShadow(QFrame.Raised)
        self.gridLayout_3 = QGridLayout(self.frame_16)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.btn_mani_av = QPushButton(self.frame_16)
        self.btn_mani_av.setObjectName(u"btn_mani_av")
        self.btn_mani_av.setMaximumSize(QSize(40, 16777215))
        self.btn_mani_av.setFont(font)
        self.btn_mani_av.setStyleSheet(u"background-color:rgb(188, 60, 75)")

        self.gridLayout_3.addWidget(self.btn_mani_av, 2, 2, 1, 1)

        self.btn_lys_paa = QPushButton(self.frame_16)
        self.btn_lys_paa.setObjectName(u"btn_lys_paa")
        self.btn_lys_paa.setMinimumSize(QSize(0, 0))
        self.btn_lys_paa.setMaximumSize(QSize(40, 16777215))
        self.btn_lys_paa.setFont(font)
        self.btn_lys_paa.setStyleSheet(u"background-color: rgb(109, 156, 113)")

        self.gridLayout_3.addWidget(self.btn_lys_paa, 0, 0, 1, 1)

        self.btn_dybde_av = QPushButton(self.frame_16)
        self.btn_dybde_av.setObjectName(u"btn_dybde_av")
        self.btn_dybde_av.setMaximumSize(QSize(40, 16777215))
        self.btn_dybde_av.setFont(font)
        self.btn_dybde_av.setStyleSheet(u"background-color:rgb(188, 60, 75)")

        self.gridLayout_3.addWidget(self.btn_dybde_av, 3, 2, 1, 1)

        self.btn_mani_paa = QPushButton(self.frame_16)
        self.btn_mani_paa.setObjectName(u"btn_mani_paa")
        self.btn_mani_paa.setMaximumSize(QSize(40, 16777215))
        self.btn_mani_paa.setFont(font)
        self.btn_mani_paa.setStyleSheet(u"background-color: rgb(109, 156, 113)")

        self.gridLayout_3.addWidget(self.btn_mani_paa, 2, 0, 1, 1)

        self.btn_lys_av = QPushButton(self.frame_16)
        self.btn_lys_av.setObjectName(u"btn_lys_av")
        self.btn_lys_av.setMaximumSize(QSize(40, 16777215))
        self.btn_lys_av.setFont(font)
        self.btn_lys_av.setStyleSheet(u"background-color:rgb(188, 60, 75)")

        self.gridLayout_3.addWidget(self.btn_lys_av, 0, 2, 1, 1)

        self.btn_helning_paa = QPushButton(self.frame_16)
        self.btn_helning_paa.setObjectName(u"btn_helning_paa")
        self.btn_helning_paa.setMaximumSize(QSize(40, 16777215))
        self.btn_helning_paa.setFont(font)
        self.btn_helning_paa.setStyleSheet(u"background-color: rgb(109, 156, 113)")

        self.gridLayout_3.addWidget(self.btn_helning_paa, 8, 0, 1, 1)

        self.btn_dybde_paa = QPushButton(self.frame_16)
        self.btn_dybde_paa.setObjectName(u"btn_dybde_paa")
        self.btn_dybde_paa.setMaximumSize(QSize(40, 16777215))
        self.btn_dybde_paa.setFont(font)
        self.btn_dybde_paa.setStyleSheet(u"background-color: rgb(109, 156, 113)")

        self.gridLayout_3.addWidget(self.btn_dybde_paa, 3, 0, 1, 1)

        self.btn_helning_av = QPushButton(self.frame_16)
        self.btn_helning_av.setObjectName(u"btn_helning_av")
        self.btn_helning_av.setMaximumSize(QSize(40, 16777215))
        self.btn_helning_av.setFont(font)
        self.btn_helning_av.setStyleSheet(u"background-color:rgb(188, 60, 75)")

        self.gridLayout_3.addWidget(self.btn_helning_av, 8, 2, 1, 1)

        self.manipulator_9 = QLabel(self.frame_16)
        self.manipulator_9.setObjectName(u"manipulator_9")
        self.manipulator_9.setFont(font)
        self.manipulator_9.setTextFormat(Qt.PlainText)

        self.gridLayout_3.addWidget(self.manipulator_9, 2, 4, 1, 1)

        self.dybdereg_5 = QLabel(self.frame_16)
        self.dybdereg_5.setObjectName(u"dybdereg_5")
        self.dybdereg_5.setFont(font)
        self.dybdereg_5.setTextFormat(Qt.PlainText)

        self.gridLayout_3.addWidget(self.dybdereg_5, 3, 4, 1, 1)

        self.helningreg_5 = QLabel(self.frame_16)
        self.helningreg_5.setObjectName(u"helningreg_5")
        self.helningreg_5.setFont(font)
        self.helningreg_5.setTextFormat(Qt.PlainText)

        self.gridLayout_3.addWidget(self.helningreg_5, 8, 4, 1, 1)

        self.lys_5 = QLabel(self.frame_16)
        self.lys_5.setObjectName(u"lys_5")
        self.lys_5.setFont(font)
        self.lys_5.setTextFormat(Qt.RichText)

        self.gridLayout_3.addWidget(self.lys_5, 0, 4, 1, 1)


        self.gridLayout_10.addWidget(self.frame_16, 0, 0, 1, 1)

        self.teller_6 = QLabel(self.container3)
        self.teller_6.setObjectName(u"teller_6")
        self.teller_6.setGeometry(QRect(20, 10, 100, 50))
        self.teller_6.setMinimumSize(QSize(0, 0))
        self.teller_6.setMaximumSize(QSize(16777215, 16777215))
        self.teller_6.setFont(font1)
        self.teller_6.setStyleSheet(u"font-size: 1.5em;")
        self.teller_6.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.circularProgressBarBase_2 = QFrame(self.container3)
        self.circularProgressBarBase_2.setObjectName(u"circularProgressBarBase_2")
        self.circularProgressBarBase_2.setGeometry(QRect(410, 30, 70, 70))
        self.circularProgressBarBase_2.setFrameShape(QFrame.NoFrame)
        self.circularProgressBarBase_2.setFrameShadow(QFrame.Raised)
        self.circularProgress_2 = QFrame(self.circularProgressBarBase_2)
        self.circularProgress_2.setObjectName(u"circularProgress_2")
        self.circularProgress_2.setGeometry(QRect(5, 5, 60, 60))
        self.circularProgress_2.setStyleSheet(u"QFrame { border-radius: 30px; background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.999 rgba(255, 0, 127, 0), stop:1.0 rgba(85, 170, 255, 255)); }")
        self.circularProgress_2.setFrameShape(QFrame.NoFrame)
        self.circularProgress_2.setFrameShadow(QFrame.Raised)
        self.circularBg_2 = QFrame(self.circularProgressBarBase_2)
        self.circularBg_2.setObjectName(u"circularBg_2")
        self.circularBg_2.setGeometry(QRect(5, 5, 60, 60))
        self.circularBg_2.setStyleSheet(u"QFrame { border-radius: 30px; background-color: rgba(77, 77, 127, 100); }")
        self.circularBg_2.setFrameShape(QFrame.NoFrame)
        self.circularBg_2.setFrameShadow(QFrame.Raised)
        self.container_2 = QFrame(self.circularProgressBarBase_2)
        self.container_2.setObjectName(u"container_2")
        self.container_2.setGeometry(QRect(10, 10, 50, 50))
        self.container_2.setStyleSheet(u"QFrame { border-radius: 25px; background-color: rgba(77, 77, 127, 255); }")
        self.container_2.setFrameShape(QFrame.StyledPanel)
        self.container_2.setFrameShadow(QFrame.Raised)
        self.labelPercentage_3 = QLabel(self.container_2)
        self.labelPercentage_3.setObjectName(u"labelPercentage_3")
        self.labelPercentage_3.setGeometry(QRect(10, 13, 31, 21))
        self.labelPercentage_3.setFont(font2)
        self.labelPercentage_3.setScaledContents(False)
        self.labelPercentage_3.setAlignment(Qt.AlignCenter)
        self.labelPercentage_3.setWordWrap(False)
        self.slider2 = QSlider(self.container3)
        self.slider2.setObjectName(u"slider2")
        self.slider2.setGeometry(QRect(370, 120, 160, 22))
        self.slider2.setMaximum(100)
        self.slider2.setOrientation(Qt.Horizontal)
        self.lys_6 = QLabel(self.container3)
        self.lys_6.setObjectName(u"lys_6")
        self.lys_6.setGeometry(QRect(550, 120, 168, 15))
        self.lys_6.setFont(font)
        self.lys_6.setTextFormat(Qt.RichText)

        self.horizontalLayout_4.addWidget(self.container3)

        self.container6 = QFrame(self.frame_6)
        self.container6.setObjectName(u"container6")
        self.container6.setMaximumSize(QSize(0, 0))
        self.container6.setAutoFillBackground(False)
        self.container6.setStyleSheet(u"QPushButton{background-color: grey; color: white;}")
        self.container6.setFrameShape(QFrame.NoFrame)
        self.container6.setFrameShadow(QFrame.Raised)
        self.circularProgressBarBase_4 = QFrame(self.container6)
        self.circularProgressBarBase_4.setObjectName(u"circularProgressBarBase_4")
        self.circularProgressBarBase_4.setGeometry(QRect(250, 80, 70, 70))
        self.circularProgressBarBase_4.setFrameShape(QFrame.NoFrame)
        self.circularProgressBarBase_4.setFrameShadow(QFrame.Raised)
        self.circularProgress_6 = QFrame(self.circularProgressBarBase_4)
        self.circularProgress_6.setObjectName(u"circularProgress_6")
        self.circularProgress_6.setGeometry(QRect(5, 5, 60, 60))
        self.circularProgress_6.setStyleSheet(u"QFrame { border-radius: 30px; background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.999 rgba(255, 0, 127, 0), stop:1.0 rgba(85, 170, 255, 255)); }")
        self.circularProgress_6.setFrameShape(QFrame.NoFrame)
        self.circularProgress_6.setFrameShadow(QFrame.Raised)
        self.circularProgressBarBase_6 = QWidget(self.container6)
        self.circularProgressBarBase_6.setObjectName(u"circularProgressBarBase_6")
        self.circularProgressBarBase_6.setGeometry(QRect(290, 230, 70, 70))
        self.circularProgress_13 = QFrame(self.circularProgressBarBase_6)
        self.circularProgress_13.setObjectName(u"circularProgress_13")
        self.circularProgress_13.setGeometry(QRect(5, 5, 60, 60))
        self.circularProgress_13.setStyleSheet(u"QFrame { border-radius: 30px; background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.999 rgba(255, 0, 127, 0), stop:1.0 rgba(85, 170, 255, 255)); }")
        self.circularProgress_13.setFrameShape(QFrame.NoFrame)
        self.circularProgress_13.setFrameShadow(QFrame.Raised)
        self.circularBg_13 = QFrame(self.circularProgressBarBase_6)
        self.circularBg_13.setObjectName(u"circularBg_13")
        self.circularBg_13.setGeometry(QRect(5, 5, 60, 60))
        self.circularBg_13.setStyleSheet(u"QFrame { border-radius: 30px; background-color: rgba(77, 77, 127, 100); }")
        self.circularBg_13.setFrameShape(QFrame.NoFrame)
        self.circularBg_13.setFrameShadow(QFrame.Raised)
        self.container_13 = QFrame(self.circularProgressBarBase_6)
        self.container_13.setObjectName(u"container_13")
        self.container_13.setGeometry(QRect(10, 10, 50, 50))
        self.container_13.setStyleSheet(u"QFrame { border-radius: 25px; background-color: rgb(77, 77, 127); }")
        self.container_13.setFrameShape(QFrame.StyledPanel)
        self.container_13.setFrameShadow(QFrame.Raised)
        self.labelPercentage_15 = QLabel(self.container_13)
        self.labelPercentage_15.setObjectName(u"labelPercentage_15")
        self.labelPercentage_15.setGeometry(QRect(10, 13, 31, 21))
        self.labelPercentage_15.setFont(font2)
        self.labelPercentage_15.setScaledContents(False)
        self.labelPercentage_15.setAlignment(Qt.AlignCenter)
        self.labelPercentage_15.setWordWrap(False)
        self.circularProgressBarBase_7 = QWidget(self.container6)
        self.circularProgressBarBase_7.setObjectName(u"circularProgressBarBase_7")
        self.circularProgressBarBase_7.setGeometry(QRect(80, 180, 70, 70))
        self.circularProgress_14 = QFrame(self.circularProgressBarBase_7)
        self.circularProgress_14.setObjectName(u"circularProgress_14")
        self.circularProgress_14.setGeometry(QRect(5, 5, 60, 60))
        self.circularProgress_14.setStyleSheet(u"QFrame { border-radius: 30px; background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.999 rgba(255, 0, 127, 0), stop:1.0 rgba(85, 170, 255, 255)); }")
        self.circularProgress_14.setFrameShape(QFrame.NoFrame)
        self.circularProgress_14.setFrameShadow(QFrame.Raised)
        self.circularBg_14 = QFrame(self.circularProgressBarBase_7)
        self.circularBg_14.setObjectName(u"circularBg_14")
        self.circularBg_14.setGeometry(QRect(5, 5, 60, 60))
        self.circularBg_14.setStyleSheet(u"QFrame { border-radius: 30px; background-color: rgba(77, 77, 127, 100); }")
        self.circularBg_14.setFrameShape(QFrame.NoFrame)
        self.circularBg_14.setFrameShadow(QFrame.Raised)
        self.container_14 = QFrame(self.circularProgressBarBase_7)
        self.container_14.setObjectName(u"container_14")
        self.container_14.setGeometry(QRect(10, 10, 50, 50))
        self.container_14.setStyleSheet(u"QFrame { border-radius: 25px; background-color: rgb(77, 77, 127); }")
        self.container_14.setFrameShape(QFrame.StyledPanel)
        self.container_14.setFrameShadow(QFrame.Raised)
        self.labelPercentage_16 = QLabel(self.container_14)
        self.labelPercentage_16.setObjectName(u"labelPercentage_16")
        self.labelPercentage_16.setGeometry(QRect(10, 13, 31, 21))
        self.labelPercentage_16.setFont(font2)
        self.labelPercentage_16.setScaledContents(False)
        self.labelPercentage_16.setAlignment(Qt.AlignCenter)
        self.labelPercentage_16.setWordWrap(False)
        self.circularProgressBarBase_9 = QWidget(self.container6)
        self.circularProgressBarBase_9.setObjectName(u"circularProgressBarBase_9")
        self.circularProgressBarBase_9.setGeometry(QRect(90, 80, 70, 70))
        self.circularProgress_16 = QFrame(self.circularProgressBarBase_9)
        self.circularProgress_16.setObjectName(u"circularProgress_16")
        self.circularProgress_16.setGeometry(QRect(5, 5, 60, 60))
        self.circularProgress_16.setStyleSheet(u"QFrame { border-radius: 30px; background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.999 rgba(255, 0, 127, 0), stop:1.0 rgba(85, 170, 255, 255)); }")
        self.circularProgress_16.setFrameShape(QFrame.NoFrame)
        self.circularProgress_16.setFrameShadow(QFrame.Raised)
        self.circularBg_16 = QFrame(self.circularProgressBarBase_9)
        self.circularBg_16.setObjectName(u"circularBg_16")
        self.circularBg_16.setGeometry(QRect(5, 5, 60, 60))
        self.circularBg_16.setStyleSheet(u"QFrame { border-radius: 30px; background-color: rgba(77, 77, 127, 100); }")
        self.circularBg_16.setFrameShape(QFrame.NoFrame)
        self.circularBg_16.setFrameShadow(QFrame.Raised)
        self.container_16 = QFrame(self.circularProgressBarBase_9)
        self.container_16.setObjectName(u"container_16")
        self.container_16.setGeometry(QRect(10, 10, 50, 50))
        self.container_16.setStyleSheet(u"QFrame { border-radius: 25px; background-color: rgb(77, 77, 127); }")
        self.container_16.setFrameShape(QFrame.StyledPanel)
        self.container_16.setFrameShadow(QFrame.Raised)
        self.labelPercentage_18 = QLabel(self.container_16)
        self.labelPercentage_18.setObjectName(u"labelPercentage_18")
        self.labelPercentage_18.setGeometry(QRect(10, 13, 31, 21))
        self.labelPercentage_18.setFont(font2)
        self.labelPercentage_18.setScaledContents(False)
        self.labelPercentage_18.setAlignment(Qt.AlignCenter)
        self.labelPercentage_18.setWordWrap(False)
        self.circularProgressBarBase_3 = QWidget(self.container6)
        self.circularProgressBarBase_3.setObjectName(u"circularProgressBarBase_3")
        self.circularProgressBarBase_3.setGeometry(QRect(250, 80, 70, 70))
        self.circularProgress_5 = QFrame(self.circularProgressBarBase_3)
        self.circularProgress_5.setObjectName(u"circularProgress_5")
        self.circularProgress_5.setGeometry(QRect(5, 5, 60, 60))
        self.circularProgress_5.setStyleSheet(u"QFrame { border-radius: 30px; background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.999 rgba(255, 0, 127, 0), stop:1.0 rgba(85, 170, 255, 255)); }")
        self.circularProgress_5.setFrameShape(QFrame.NoFrame)
        self.circularProgress_5.setFrameShadow(QFrame.Raised)
        self.circularBg_5 = QFrame(self.circularProgressBarBase_3)
        self.circularBg_5.setObjectName(u"circularBg_5")
        self.circularBg_5.setGeometry(QRect(5, 5, 60, 60))
        self.circularBg_5.setStyleSheet(u"QFrame { border-radius: 30px; background-color: rgba(77, 77, 127, 100); }")
        self.circularBg_5.setFrameShape(QFrame.NoFrame)
        self.circularBg_5.setFrameShadow(QFrame.Raised)
        self.container_5 = QFrame(self.circularProgressBarBase_3)
        self.container_5.setObjectName(u"container_5")
        self.container_5.setGeometry(QRect(10, 10, 50, 50))
        self.container_5.setStyleSheet(u"QFrame { border-radius: 25px; background-color: rgb(77, 77, 127); }")
        self.container_5.setFrameShape(QFrame.StyledPanel)
        self.container_5.setFrameShadow(QFrame.Raised)
        self.labelPercentage_7 = QLabel(self.container_5)
        self.labelPercentage_7.setObjectName(u"labelPercentage_7")
        self.labelPercentage_7.setGeometry(QRect(10, 13, 31, 21))
        self.labelPercentage_7.setFont(font2)
        self.labelPercentage_7.setScaledContents(False)
        self.labelPercentage_7.setAlignment(Qt.AlignCenter)
        self.labelPercentage_7.setWordWrap(False)
        self.gridLayout_4 = QGridLayout(self.container6)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.motorpaadrag = QLabel(self.container6)
        self.motorpaadrag.setObjectName(u"motorpaadrag")
        self.motorpaadrag.setMaximumSize(QSize(1000, 50))
        self.motorpaadrag.setFont(font1)
        self.motorpaadrag.setTextFormat(Qt.PlainText)

        self.gridLayout_4.addWidget(self.motorpaadrag, 0, 0, 1, 1)

        self.circularProgressBarBase_10 = QWidget(self.container6)
        self.circularProgressBarBase_10.setObjectName(u"circularProgressBarBase_10")
        self.circularProgress_17 = QFrame(self.circularProgressBarBase_10)
        self.circularProgress_17.setObjectName(u"circularProgress_17")
        self.circularProgress_17.setGeometry(QRect(5, 5, 60, 60))
        self.circularProgress_17.setStyleSheet(u"QFrame { border-radius: 30px; background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.999 rgba(255, 0, 127, 0), stop:1.0 rgba(85, 170, 255, 255)); }")
        self.circularProgress_17.setFrameShape(QFrame.NoFrame)
        self.circularProgress_17.setFrameShadow(QFrame.Raised)
        self.circularBg_17 = QFrame(self.circularProgressBarBase_10)
        self.circularBg_17.setObjectName(u"circularBg_17")
        self.circularBg_17.setGeometry(QRect(5, 5, 60, 60))
        self.circularBg_17.setStyleSheet(u"QFrame { border-radius: 30px; background-color: rgba(77, 77, 127, 100); }")
        self.circularBg_17.setFrameShape(QFrame.NoFrame)
        self.circularBg_17.setFrameShadow(QFrame.Raised)
        self.container_17 = QFrame(self.circularProgressBarBase_10)
        self.container_17.setObjectName(u"container_17")
        self.container_17.setGeometry(QRect(10, 10, 50, 50))
        self.container_17.setStyleSheet(u"QFrame { border-radius: 25px; background-color: rgb(77, 77, 127); }")
        self.container_17.setFrameShape(QFrame.StyledPanel)
        self.container_17.setFrameShadow(QFrame.Raised)
        self.labelPercentage_19 = QLabel(self.container_17)
        self.labelPercentage_19.setObjectName(u"labelPercentage_19")
        self.labelPercentage_19.setGeometry(QRect(10, 13, 31, 21))
        self.labelPercentage_19.setFont(font2)
        self.labelPercentage_19.setScaledContents(False)
        self.labelPercentage_19.setAlignment(Qt.AlignCenter)
        self.labelPercentage_19.setWordWrap(False)

        self.gridLayout_4.addWidget(self.circularProgressBarBase_10, 1, 0, 1, 1)

        self.circularProgressBarBase_11 = QWidget(self.container6)
        self.circularProgressBarBase_11.setObjectName(u"circularProgressBarBase_11")
        self.circularProgress_19 = QFrame(self.circularProgressBarBase_11)
        self.circularProgress_19.setObjectName(u"circularProgress_19")
        self.circularProgress_19.setGeometry(QRect(5, 5, 60, 60))
        self.circularProgress_19.setStyleSheet(u"QFrame { border-radius: 30px; background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.999 rgba(255, 0, 127, 0), stop:1.0 rgba(85, 170, 255, 255)); }")
        self.circularProgress_19.setFrameShape(QFrame.NoFrame)
        self.circularProgress_19.setFrameShadow(QFrame.Raised)
        self.circularBg_18 = QFrame(self.circularProgressBarBase_11)
        self.circularBg_18.setObjectName(u"circularBg_18")
        self.circularBg_18.setGeometry(QRect(5, 5, 60, 60))
        self.circularBg_18.setStyleSheet(u"QFrame { border-radius: 30px; background-color: rgba(77, 77, 127, 100); }")
        self.circularBg_18.setFrameShape(QFrame.NoFrame)
        self.circularBg_18.setFrameShadow(QFrame.Raised)
        self.container_18 = QFrame(self.circularProgressBarBase_11)
        self.container_18.setObjectName(u"container_18")
        self.container_18.setGeometry(QRect(10, 10, 50, 50))
        self.container_18.setStyleSheet(u"QFrame { border-radius: 25px; background-color: rgb(77, 77, 127); }")
        self.container_18.setFrameShape(QFrame.StyledPanel)
        self.container_18.setFrameShadow(QFrame.Raised)
        self.labelPercentage_20 = QLabel(self.container_18)
        self.labelPercentage_20.setObjectName(u"labelPercentage_20")
        self.labelPercentage_20.setGeometry(QRect(10, 13, 31, 21))
        self.labelPercentage_20.setFont(font2)
        self.labelPercentage_20.setScaledContents(False)
        self.labelPercentage_20.setAlignment(Qt.AlignCenter)
        self.labelPercentage_20.setWordWrap(False)

        self.gridLayout_4.addWidget(self.circularProgressBarBase_11, 1, 1, 1, 1)

        self.frame_3 = QFrame(self.container6)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setMaximumSize(QSize(16777215, 16777215))
        self.frame_3.setFrameShape(QFrame.NoFrame)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.label_18 = QLabel(self.frame_3)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(100, 0, 181, 231))
        self.label_18.setPixmap(QPixmap(u"images/thrustere.png"))
        self.label_18.setScaledContents(True)
        self.circularProgressBarBase_5 = QFrame(self.frame_3)
        self.circularProgressBarBase_5.setObjectName(u"circularProgressBarBase_5")
        self.circularProgressBarBase_5.setGeometry(QRect(230, 130, 70, 70))
        self.circularProgress_11 = QFrame(self.circularProgressBarBase_5)
        self.circularProgress_11.setObjectName(u"circularProgress_11")
        self.circularProgress_11.setGeometry(QRect(5, 5, 60, 60))
        self.circularProgress_11.setStyleSheet(u"QFrame { border-radius: 30px; background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.999 rgba(255, 0, 127, 0), stop:1.0 rgba(85, 170, 255, 255)); }")
        self.circularProgress_11.setFrameShape(QFrame.NoFrame)
        self.circularProgress_11.setFrameShadow(QFrame.Raised)
        self.circularBg_11 = QFrame(self.circularProgressBarBase_5)
        self.circularBg_11.setObjectName(u"circularBg_11")
        self.circularBg_11.setGeometry(QRect(5, 5, 60, 60))
        self.circularBg_11.setStyleSheet(u"QFrame { border-radius: 30px; background-color: rgba(77, 77, 127, 100); }")
        self.circularBg_11.setFrameShape(QFrame.NoFrame)
        self.circularBg_11.setFrameShadow(QFrame.Raised)
        self.container_11 = QFrame(self.circularProgressBarBase_5)
        self.container_11.setObjectName(u"container_11")
        self.container_11.setGeometry(QRect(10, 10, 50, 50))
        self.container_11.setStyleSheet(u"QFrame { border-radius: 25px; background-color: rgba(77, 77, 127, 255); }")
        self.container_11.setFrameShape(QFrame.StyledPanel)
        self.container_11.setFrameShadow(QFrame.Raised)
        self.labelPercentage_13 = QLabel(self.container_11)
        self.labelPercentage_13.setObjectName(u"labelPercentage_13")
        self.labelPercentage_13.setGeometry(QRect(10, 13, 31, 21))
        self.labelPercentage_13.setFont(font2)
        self.labelPercentage_13.setScaledContents(False)
        self.labelPercentage_13.setAlignment(Qt.AlignCenter)
        self.labelPercentage_13.setWordWrap(False)
        self.circularProgressBarBase_8 = QFrame(self.frame_3)
        self.circularProgressBarBase_8.setObjectName(u"circularProgressBarBase_8")
        self.circularProgressBarBase_8.setGeometry(QRect(20, 190, 70, 70))
        self.circularProgress_15 = QFrame(self.circularProgressBarBase_8)
        self.circularProgress_15.setObjectName(u"circularProgress_15")
        self.circularProgress_15.setGeometry(QRect(5, 5, 60, 60))
        self.circularProgress_15.setStyleSheet(u"QFrame { border-radius: 30px; background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.999 rgba(255, 0, 127, 0), stop:1.0 rgba(85, 170, 255, 255)); }")
        self.circularProgress_15.setFrameShape(QFrame.NoFrame)
        self.circularProgress_15.setFrameShadow(QFrame.Raised)
        self.circularBg_15 = QFrame(self.circularProgressBarBase_8)
        self.circularBg_15.setObjectName(u"circularBg_15")
        self.circularBg_15.setGeometry(QRect(5, 5, 60, 60))
        self.circularBg_15.setStyleSheet(u"QFrame { border-radius: 30px; background-color: rgba(77, 77, 127, 100); }")
        self.circularBg_15.setFrameShape(QFrame.NoFrame)
        self.circularBg_15.setFrameShadow(QFrame.Raised)
        self.container_15 = QFrame(self.circularProgressBarBase_8)
        self.container_15.setObjectName(u"container_15")
        self.container_15.setGeometry(QRect(10, 10, 50, 50))
        self.container_15.setStyleSheet(u"QFrame { border-radius: 25px; background-color: rgba(77, 77, 127, 255); }")
        self.container_15.setFrameShape(QFrame.StyledPanel)
        self.container_15.setFrameShadow(QFrame.Raised)
        self.labelPercentage_17 = QLabel(self.container_15)
        self.labelPercentage_17.setObjectName(u"labelPercentage_17")
        self.labelPercentage_17.setGeometry(QRect(10, 13, 31, 21))
        self.labelPercentage_17.setFont(font2)
        self.labelPercentage_17.setScaledContents(False)
        self.labelPercentage_17.setAlignment(Qt.AlignCenter)
        self.labelPercentage_17.setWordWrap(False)

        self.gridLayout_4.addWidget(self.frame_3, 2, 0, 1, 2)


        self.horizontalLayout_4.addWidget(self.container6)


        self.verticalLayout_11.addWidget(self.frame_6)

        self.container4 = QFrame(self.frame_2)
        self.container4.setObjectName(u"container4")
        self.container4.setMaximumSize(QSize(16777215, 16777215))
        self.container4.setAutoFillBackground(False)
        self.container4.setStyleSheet(u"QPushButton{background-color: grey; color: white;}")
        self.container4.setFrameShape(QFrame.NoFrame)
        self.container4.setFrameShadow(QFrame.Raised)
        self.verticalLayout_7 = QVBoxLayout(self.container4)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.sensorinfo_5 = QLabel(self.container4)
        self.sensorinfo_5.setObjectName(u"sensorinfo_5")
        self.sensorinfo_5.setMaximumSize(QSize(16777215, 16777215))
        self.sensorinfo_5.setFont(font1)
        self.sensorinfo_5.setTextFormat(Qt.RichText)

        self.verticalLayout_7.addWidget(self.sensorinfo_5)

        self.lekkasje_5 = QLabel(self.container4)
        self.lekkasje_5.setObjectName(u"lekkasje_5")
        self.lekkasje_5.setMaximumSize(QSize(16777215, 16777215))
        self.lekkasje_5.setFont(font)
        self.lekkasje_5.setFrameShadow(QFrame.Sunken)
        self.lekkasje_5.setTextFormat(Qt.RichText)

        self.verticalLayout_7.addWidget(self.lekkasje_5)

        self.lekkasje_6 = QLabel(self.container4)
        self.lekkasje_6.setObjectName(u"lekkasje_6")
        self.lekkasje_6.setMaximumSize(QSize(16777215, 16777215))
        self.lekkasje_6.setFont(font)
        self.lekkasje_6.setFrameShadow(QFrame.Sunken)
        self.lekkasje_6.setTextFormat(Qt.RichText)

        self.verticalLayout_7.addWidget(self.lekkasje_6)

        self.frame_5 = QFrame(self.container4)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setFrameShape(QFrame.NoFrame)
        self.frame_5.setFrameShadow(QFrame.Raised)

        self.verticalLayout_7.addWidget(self.frame_5)


        self.verticalLayout_11.addWidget(self.container4)


        self.gridLayout_13.addWidget(self.frame_2, 0, 0, 1, 1)

        self.stackedWidget.addWidget(self.informasjon)

        self.gridLayout_12.addWidget(self.stackedWidget, 0, 0, 1, 1)


        self.verticalLayout.addWidget(self.content_bar)


        self.gridLayout_7.addWidget(self.drop_shadow_frame, 0, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionNew.setText(QCoreApplication.translate("MainWindow", u"New", None))
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"Open", None))
        self.actionCopy.setText(QCoreApplication.translate("MainWindow", u"Copy", None))
        self.actionPaste.setText(QCoreApplication.translate("MainWindow", u"Paste", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u" FRONTKAMERA", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u" BUNNKAMERA", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u" KONTROLLER", None))
        self.pushButton_6.setText(QCoreApplication.translate("MainWindow", u"INFORMASJON", None))
        self.label.setText("")
        self.label_title_2.setText(QCoreApplication.translate("MainWindow", u"UiS Subsea", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"ENDRE KONTROLLER-KNAPPER", None))
        self.label_4.setText("")
        self.mainpulator.setText(QCoreApplication.translate("MainWindow", u"MANIPULATOR", None))
        self.label_19.setText("")
        self.labelPercentage_22.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:14pt;\">0</span><span style=\" font-size:14pt; vertical-align:super;\">%</span></p></body></html>", None))
        self.labelPercentage_23.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:14pt;\">0</span><span style=\" font-size:14pt; vertical-align:super;\">%</span></p></body></html>", None))
        self.labelPercentage_25.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:14pt;\">0</span><span style=\" font-size:14pt; vertical-align:super;\">%</span></p></body></html>", None))
        self.bildebehandling.setText(QCoreApplication.translate("MainWindow", u"BILDEBEHANDLING", None))
        self.btn_korallrev.setText(QCoreApplication.translate("MainWindow", u"Korallrev", None))
        self.label_bilde2.setText(QCoreApplication.translate("MainWindow", u"Siste bilde analyseres", None))
        self.label_bilde1.setText(QCoreApplication.translate("MainWindow", u"Siste bilde analyseres", None))
        self.label_bilde3.setText(QCoreApplication.translate("MainWindow", u"Siste bilde analyseres", None))
        self.btn_fotomoasaikk.setText(QCoreApplication.translate("MainWindow", u"Fotomoasaikk", None))
        self.btn_havbunn.setText(QCoreApplication.translate("MainWindow", u"Havbunn", None))
        self.labelPercentage.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:14pt;\">0</span><span style=\" font-size:14pt; vertical-align:super;\">%</span></p></body></html>", None))
        self.kamera_6.setText(QCoreApplication.translate("MainWindow", u"KAMERA", None))
        self.btn_frontkamera.setText(QCoreApplication.translate("MainWindow", u"Ta bilde frontkamera", None))
        self.btn_havbunnskamera.setText(QCoreApplication.translate("MainWindow", u"Ta bilde havbunnskamera", None))
        self.btn_slettsistebilde.setText(QCoreApplication.translate("MainWindow", u"Slett det siste bildet", None))
        self.label_2.setText("")
        self.kontroller_7.setText(QCoreApplication.translate("MainWindow", u"KJ\u00d8RING", None))
        self.btn_manuell.setText(QCoreApplication.translate("MainWindow", u"Manuell", None))
        self.btn_auto.setText(QCoreApplication.translate("MainWindow", u"Auto", None))
        self.label_spenning.setText(QCoreApplication.translate("MainWindow", u"Spenning:", None))
        self.temp_vann.setText(QCoreApplication.translate("MainWindow", u"-----", None))
        self.label_temp_vann.setText(QCoreApplication.translate("MainWindow", u"Temp vann:", None))
        self.label_tid.setText(QCoreApplication.translate("MainWindow", u"Tid:", None))
        self.tid.setText(QCoreApplication.translate("MainWindow", u"00:00:00", None))
        self.label_dybde.setText(QCoreApplication.translate("MainWindow", u"Dybde:", None))
        self.spenning.setText(QCoreApplication.translate("MainWindow", u"-----", None))
        self.label_orientering.setText(QCoreApplication.translate("MainWindow", u"Orientering:", None))
        self.strom2.setText(QCoreApplication.translate("MainWindow", u"-----", None))
        self.label_strom1.setText(QCoreApplication.translate("MainWindow", u"Str\u00f8m 1:", None))
        self.label_strom.setText(QCoreApplication.translate("MainWindow", u"Str\u00f8m 2:", None))
        self.dybde.setText(QCoreApplication.translate("MainWindow", u"-----", None))
        self.orientering.setText(QCoreApplication.translate("MainWindow", u"-----", None))
        self.strom1.setText(QCoreApplication.translate("MainWindow", u"-----", None))
        self.btn_mani_av.setText(QCoreApplication.translate("MainWindow", u"Av", None))
        self.btn_lys_paa.setText(QCoreApplication.translate("MainWindow", u"P\u00e5", None))
        self.btn_dybde_av.setText(QCoreApplication.translate("MainWindow", u"Av", None))
        self.btn_mani_paa.setText(QCoreApplication.translate("MainWindow", u"P\u00e5", None))
        self.btn_lys_av.setText(QCoreApplication.translate("MainWindow", u"Av", None))
        self.btn_helning_paa.setText(QCoreApplication.translate("MainWindow", u"P\u00e5", None))
        self.btn_dybde_paa.setText(QCoreApplication.translate("MainWindow", u"P\u00e5", None))
        self.btn_helning_av.setText(QCoreApplication.translate("MainWindow", u"Av", None))
        self.manipulator_9.setText(QCoreApplication.translate("MainWindow", u"Manipulator", None))
        self.dybdereg_5.setText(QCoreApplication.translate("MainWindow", u"Dybde regulator", None))
        self.helningreg_5.setText(QCoreApplication.translate("MainWindow", u"Helningsregulator", None))
        self.lys_5.setText(QCoreApplication.translate("MainWindow", u"Lys", None))
        self.teller_6.setText(QCoreApplication.translate("MainWindow", u"ROV", None))
        self.labelPercentage_3.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:14pt;\">0</span><span style=\" font-size:14pt; vertical-align:super;\">%</span></p></body></html>", None))
        self.lys_6.setText(QCoreApplication.translate("MainWindow", u"Lys", None))
        self.labelPercentage_15.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:14pt;\">0</span><span style=\" font-size:14pt; vertical-align:super;\">%</span></p></body></html>", None))
        self.labelPercentage_16.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:14pt;\">0</span><span style=\" font-size:14pt; vertical-align:super;\">%</span></p></body></html>", None))
        self.labelPercentage_18.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:14pt;\">0</span><span style=\" font-size:14pt; vertical-align:super;\">%</span></p></body></html>", None))
        self.labelPercentage_7.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:14pt;\">0</span><span style=\" font-size:14pt; vertical-align:super;\">%</span></p></body></html>", None))
        self.motorpaadrag.setText(QCoreApplication.translate("MainWindow", u"MOTORP\u00c5DRAG", None))
        self.labelPercentage_19.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:14pt;\">0</span><span style=\" font-size:14pt; vertical-align:super;\">%</span></p></body></html>", None))
        self.labelPercentage_20.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:14pt;\">0</span><span style=\" font-size:14pt; vertical-align:super;\">%</span></p></body></html>", None))
        self.label_18.setText("")
        self.labelPercentage_13.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:14pt;\">0</span><span style=\" font-size:14pt; vertical-align:super;\">%</span></p></body></html>", None))
        self.labelPercentage_17.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:14pt;\">0</span><span style=\" font-size:14pt; vertical-align:super;\">%</span></p></body></html>", None))
        self.sensorinfo_5.setText(QCoreApplication.translate("MainWindow", u"SENSOR INFORMASJON", None))
        self.lekkasje_5.setText(QCoreApplication.translate("MainWindow", u"Lekasje:", None))
        self.lekkasje_6.setText(QCoreApplication.translate("MainWindow", u"Temperatur:", None))
    # retranslateUi

